<Solution name="PMAC">
	<Project name="PARAMOUR MULTI-ANIMATION CONTROLLER (PMAC)" path="PARAMOUR MULTI-ANIMATION CONTROLLER (PMAC)\PARAMOUR MULTI-ANIMATION CONTROLLER (PMAC).prj" active="true"/>
</Solution>
